### ISSUE TITLE
1804Week17 工作安排

### ISSUE THREAD

**Issue by AwesomeJason** [AwesomeJason/ChiliEducationReview#1]
# 1804Week17D2 工作安排

## 安排说明

因新版 H5 已经出来了，需要内容填充后尽快上线，所以我们今天&明天的工作重心临时调整一下，变为「从过去的文章中筛选符合新规划的文章，重新排列组合」

## 待办事项

- 填充 5 个栏目：5*40
- 填充推荐栏目：40
- 专题 1-2 个

## 时间节点&分工

周二下班前完成栏目填充，并汇报空缺内容类目、数量

- Team1：丹阳 + 陈丽，负责「推荐 + 自我教育 + 学科教育」
- Team2：阿飞 + 甄祯，负责「职场教育 + 特色教育 + 教育快报」
- Team3：李亮，负责「专题」

## 栏目说明

- 推荐：聚合类
- 自我教育：如思考方式、世界观等；
- 学科教育：如英语、计算机等；
- 职场教育：如工作习惯等
- 特色教育：其他类教育，如国学、早教等；
- 教育快报：教育资讯、新闻等

## 标题说明

1804Week17D2 的意思是 18 年 4 月第 17 周第 2 天。

**Comment by ChenConnie** [comment]
1.配合H5上线的内容填充（筛选并编辑发布学科教育和自我教育栏目的文章共80篇）
2.UI脑图分发反馈：贴吧19个（需要脑图）
3.参加内容部培训

**Comment by z1023z** [comment]
1.H5上线内容的填充（特色教育和教育快讯共80篇）
2.内容运行培训

**Comment by AwesomeJason** [comment]
# 1804Week17D4 工作安排

## 安排说明
- 完成专题上线；
- 熟悉新工作模式&工具；
- 开始主攻「自我教育」和「职场教育」原创文章 + 专题

**Comment by AwesomeJason** [comment]
# 1804Week17D6 工作安排

## 安排说明

全面专注于「自我教育」和「职场教育」原创文章 + 专题，优先级最高。

附：[App2.0 上线专题方向规划](https://github.com/AwesomeJason/ChiliEducationReview/blob/master/TOPIC/App2.0%20%E4%B8%8A%E7%BA%BF%E4%B8%93%E9%A2%98.md)

## 目前进度

- 原创文章：3/60
	- 自我教育：2/30
	- 职场教育：1/30
- 编辑文章：0/20
- 优秀专题：0/10

## 方向

从4月27日开始，每个工作日，每个方向完成 3 篇原创稿件 + 3 篇编辑，其中：

- Team1：丹阳 + 陈丽，
- Team2：阿飞 + 甄禛，

## 分工到人工作量

- 李亮：每日不少于 8 个选题方向 + 粗略框架 + 撰写教程 + 解决、处理各种问题
- 丹阳：每日 2 篇原创 + 2 篇编辑 + 修订实习生原创文章
- 阿飞：每日 2 篇原创 + 2 篇编辑 + 专题选题、上线
- 陈丽：每日 1 篇原创 + 1 篇编辑 + 查找、整理资料
- 甄禛：每日 1 篇原创 + 1 篇编辑 + 查找、整理资料
